let dados = [
    {
        nome: "Harry Potter",
        descricao: "Órfão criado pelos tios trouxas, Harry Potter descobre aos 11 anos que é um bruxo e está destinado a grandes coisas. Corajoso e leal, ele possui uma forte conexão com o Lorde das Trevas, o que o torna um alvo constante. Habilidoso em Defesa Contra as Artes das Trevas, Harry é o procurador da equipe de quadribol de Grifinória.",
        familia: "Potter",
        casa: "Grifinória",
        idade: 17,
        imagem: "./img/Harry_Potter.webp",
        habilidades: ["Patronus: um cervo", "Alohomora", "Expelliarmus"],
    },
    {
        nome: "Hermione Granger",
        descricao: "Mestiça de origem trouxa, Hermione é uma das bruxas mais inteligentes de sua geração. Extremamente estudiosa e sempre com respostas na ponta da língua, ela é conhecida por sua habilidade em feitiços complexos e por ser uma amiga leal de Harry e Rony.",
        familia: "Granger",
        casa: "Grifinória",
        idade: 17,
        imagem: "./img/Hermione_Granger.webp",
        habilidades: ["Levicorpus", "Protego", "Feitiço do Patrono: uma lontra"],
    },
    {
        nome: "Ron Weasley",
        descricao: "Amigo leal e divertido de Harry Potter, Rony vem de uma família de bruxos conhecida, os Weasley. Embora inseguro sobre seu lugar no mundo, ele demonstra coragem em momentos críticos. Rony é também o goleiro da equipe de quadribol da Grifinória.",
        familia: "Weasley",
        casa: "Grifinória",
        idade: 17,
        imagem: "./img/Ron_Weasley.webp",
        habilidades: ["Xadrez de bruxo", "Alohomora", "Lumos"],
    },
    {
        nome: "Alvo Dumbledore",
        descricao: "Considerado o maior bruxo de todos os tempos, Dumbledore foi diretor de Hogwarts e mentor de Harry Potter. Sábio, justo e poderoso, ele foi o principal oponente de Voldemort. Sua habilidade com magia é lendária.",
        familia: "Dumbledore",
        casa: "Grifinória",
        idade: 115,
        imagem: "./img/Alvo_Dumbledore.webp",
        habilidades: ["Transfiguração", "Feitiço do Patrono: uma fênix", "Legilimência"],
    },
    {
        nome: "Severo Snape",
        descricao: "Ex-membro dos Comensais da Morte, Severo Snape era mestre em Poções e, mais tarde, em Defesa Contra as Artes das Trevas. Ele viveu uma vida complexa, sempre caminhando na linha entre o bem e o mal, até sua lealdade final ser revelada.",
        familia: "Snape",
        casa: "Sonserina",
        idade: 38,
        imagem: "./img/Severo_Snape.webp",
        habilidades: ["Oclumência", "Legilimência", "Sectumsempra"],
    },
    {
        nome: "Lord Voldemort",
        descricao: "Tom Marvolo Riddle, mais conhecido como Lord Voldemort, é o maior bruxo das trevas de todos os tempos. Ele possui uma imensa habilidade em magia negra, obsessão por imortalidade, e é o criador de várias Horcruxes.",
        familia: "Gaunt",
        casa: "Sonserina",
        idade: 71,
        imagem: "./img/Lord_Voldemort.webp",
        habilidades: ["Feitiços das Trevas", "Legilimência", "Criação de Horcruxes"],
    },
    {
        nome: "Bellatrix Lestrange",
        descricao: "Seguidora leal de Voldemort, Bellatrix é uma bruxa extremamente perigosa, sádica e poderosa. Ela é especialmente habilidosa em feitiços das trevas e maldições imperdoáveis.",
        familia: "Lestrange",
        casa: "Sonserina",
        idade: 47,
        imagem: "./img/Bellatrix_Lestrange.webp",
        habilidades: ["Cruciatus", "Avada Kedavra", "Transfiguração das Trevas"],
    },
    {
        nome: "Sirius Black",
        descricao: "Sirius Black, padrinho de Harry, foi injustamente condenado à prisão em Azkaban por assassinato. Ele é um animago, capaz de se transformar em um grande cão negro, e foi um dos amigos mais próximos de Tiago Potter.",
        familia: "Black",
        casa: "Grifinória",
        idade: 36,
        imagem: "./img/Sirius_Black.webp",
        habilidades: ["Animagia", "Protego", "Transfiguração"],
    },
    {
        nome: "Remus Lupin",
        descricao: "Remus Lupin, professor de Defesa Contra as Artes das Trevas, é um lobisomem que mantém sua condição sob controle com poções. Ele é conhecido por sua paciência e bondade, sendo um grande aliado de Harry.",
        familia: "Lupin",
        casa: "Grifinória",
        idade: 37,
        imagem: "./img/Remus_Lupin.webp",
        habilidades: ["Metamorfomagia", "Feitiço do Patrono: um lobo", "Alohomora"],
    },
    {
        nome: "Minerva McGonagall",
        descricao: "McGonagall é a vice-diretora de Hogwarts e chefe da Casa Grifinória. Ela é uma bruxa extremamente habilidosa, especialmente em transfiguração, e é respeitada por sua autoridade e lealdade à escola.",
        familia: "McGonagall",
        casa: "Grifinória",
        idade: 85,
        imagem: "./img/Minerva_McGonagall.webp",
        habilidades: ["Transfiguração", "Animagia", "Protego"],
    },
    {
        nome: "Ninfadora Tonks",
        descricao: "Tonks é uma aurora e membro da Ordem da Fênix. Ela é uma metamorfomaga, capaz de mudar sua aparência à vontade. Alegre e corajosa, ela é uma das principais combatentes contra as forças das trevas.",
        familia: "Tonks",
        casa: "Lufa-Lufa",
        idade: 25,
        imagem: "./img/Ninfadora_Tonks.webp",
        habilidades: ["Metamorfomagia", "Alohomora", "Protego"],
    },
    {
        nome: "Draco Malfoy",
        descricao: "Filho de Lucius e Narcisa Malfoy, Draco foi criado em uma família de sangue puro e tornou-se o principal antagonista de Harry em Hogwarts. Embora tenha sido relutante em seu papel nos Comensais da Morte, ele é habilidoso em feitiços das trevas.",
        familia: "Malfoy",
        casa: "Sonserina",
        idade: 17,
        imagem: "./img/Draco_Malfoy.webp",
        habilidades: ["Sectumsempra", "Expelliarmus", "Feitiços das Trevas"],
    },
    {
        nome: "Lucius Malfoy",
        descricao: "Pai de Draco e membro influente dos Comensais da Morte, Lucius Malfoy é um bruxo rico e poderoso. Ele é conhecido por sua lealdade a Voldemort, bem como por sua habilidade em magia negra.",
        familia: "Malfoy",
        casa: "Sonserina",
        idade: 50,
        imagem: "./img/Lucius_Malfoy.webp",
        habilidades: ["Feitiços das Trevas", "Legilimência", "Transfiguração"],
    },
    {
        nome: "Narcisa Malfoy",
        descricao: "Esposa de Lucius e mãe de Draco, Narcisa é uma bruxa leal à sua família e profundamente protetora com seu filho. Ela não é diretamente envolvida em atos das trevas, mas suas conexões a mantêm próxima do círculo de Voldemort.",
        familia: "Malfoy",
        casa: "Sonserina",
        idade: 48,
        imagem: "./img/Narcisa_Malfoy.webp",
        habilidades: ["Ocultismo", "Feitiço de Aparatação", "Protego"],
    },
    {
        nome: "Cedrico Diggory",
        descricao: "Cedrico foi o campeão de Hogwarts no Torneio Tribruxo e é lembrado por sua bravura e habilidade. Ele era um estudante talentoso da Lufa-Lufa e demonstrou grande integridade durante a competição.",
        familia: "Diggory",
        casa: "Lufa-Lufa",
        idade: 17,
        imagem: "./img/Cedrico_Diggory.webp",
        habilidades: ["Aparatação", "Expelliarmus", "Feitiço da Bolha"],
    },
    {
        nome: "Cho Chang",
        descricao: "Cho Chang era uma estudante da Corvinal e um dos interesses amorosos de Harry Potter. Ela também foi uma talentosa jogadora de quadribol, atuando como apanhadora no time de sua casa.",
        familia: "Chang",
        casa: "Corvinal",
        idade: 17,
        imagem: "./img/Cho_Chang.webp",
        habilidades: ["Patronus: um cisne", "Alohomora", "Lumos"],
    },
    {
        nome: "Luna Lovegood",
        descricao: "Luna é uma estudante excêntrica da Corvinal, conhecida por suas crenças em criaturas mágicas incomuns e seu comportamento único. Apesar de sua aparência sonhadora, ela é extremamente corajosa e leal a seus amigos.",
        familia: "Lovegood",
        casa: "Corvinal",
        idade: 16,
        imagem: "./img/Luna_Lovegood.webp",
        habilidades: ["Feitiço do Patrono: uma lebre", "Protego", "Feitiço de Levitação"],
    },
    {
        nome: "Neville Longbottom",
        descricao: "Originalmente tímido e desajeitado, Neville floresceu como um dos heróis da Batalha de Hogwarts. Ele se destacou em Herbologia e foi fundamental na destruição de uma das Horcruxes de Voldemort.",
        familia: "Longbottom",
        casa: "Grifinória",
        idade: 17,
        imagem: "./img/Neville_Longbottom.webp",
        habilidades: ["Herbologia", "Expelliarmus", "Feitiço de Aparatação"],
    },
    {
        nome: "Filius Flitwick",
        descricao: "Professor de Feitiços e chefe da Corvinal, Flitwick é conhecido por sua habilidade em feitiços complexos e seu comportamento alegre. Ele é um mestre em duelos e desempenhou um papel crucial na defesa de Hogwarts.",
        familia: "Flitwick",
        casa: "Corvinal",
        idade: 90,
        imagem: "./img/Filius_Flitwick.webp",
        habilidades: ["Feitiço do Escudo", "Alohomora", "Levicorpus"],
    },
    {
        nome: "Horácio Slughorn",
        descricao: "Slughorn é um ex-professor de Poções em Hogwarts, conhecido por seu talento em identificar jovens promissores e formar uma rede de ex-alunos influentes. Ele também foi um dos mentores de Tom Riddle.",
        familia: "Slughorn",
        casa: "Sonserina",
        idade: 80,
        imagem: "./img/Horacio_Slughorn.webp",
        habilidades: ["Poções", "Alohomora", "Feitiço do Ocultamento"],
    },
    {
        nome: "Rita Skeeter",
        descricao: "Jornalista escandalosa e habilidosa em explorar a vida pessoal dos outros, Rita Skeeter é uma animaga não registrada, capaz de se transformar em um besouro para obter informações privilegiadas.",
        familia: "Skeeter",
        casa: "Desconhecida",
        idade: 43,
        imagem: "./img/Rita_Skeeter.webp",
        habilidades: ["Animagia", "Feitiço de Escrita", "Feitiço do Confundo"],
    },
    {
        nome: "Gilderoy Lockhart",
        descricao: "Lockhart foi um autor famoso e brevemente professor de Defesa Contra as Artes das Trevas. Ele era um grande mentiroso, apropriando-se das façanhas de outros bruxos, até que um feitiço de memória que lançou sobre si mesmo falhou.",
        familia: "Lockhart",
        casa: "Corvinal",
        idade: 40,
        imagem: "./img/Gilderoy_Lockhart.webp",
        habilidades: ["Obliviate", "Protego", "Feitiços de Encantamento"],
    },
    {
        nome: "Aberforth Dumbledore",
        descricao: "Irmão mais novo de Alvo Dumbledore, Aberforth é um bruxo talentoso, embora tenha vivido à sombra do irmão. Ele era o dono do bar Cabeça de Javali e desempenhou um papel importante na Batalha de Hogwarts.",
        familia: "Dumbledore",
        casa: "Grifinória",
        idade: 110,
        imagem: "./img/Aberforth_Dumbledore.webp",
        habilidades: ["Feitiços de Defesa", "Animagia", "Feitiço do Patrono: uma cabra"],
    },
    {
        nome: "Viktor Krum",
        descricao: "Famoso apanhador da equipe de quadribol da Bulgária, Krum também foi um dos campeões do Torneio Tribruxo. Ele é conhecido por sua habilidade no voo e seu papel crucial na competição.",
        familia: "Krum",
        casa: "Durmstrang",
        idade: 18,
        imagem: "./img/Viktor_Krum.webp",
        habilidades: ["Quadribol", "Alohomora", "Feitiço de Aparatação"],
    },
    {
        nome: "Xenofílio Lovegood",
        descricao: "Pai de Luna Lovegood e editor da revista O Pasquim. Embora excêntrico, ele era um grande defensor das Relíquias da Morte e desempenhou um papel crucial na história de Harry Potter.",
        familia: "Lovegood",
        casa: "Desconhecida",
        idade: 50,
        imagem: "./img/Xenofílio_Lovegood.webp",
        habilidades: ["Aparatação", "Encantamentos", "Magia de Projeção"],
    },
    {
        nome: "Arthur Weasley",
        descricao: "Pai da família Weasley, Arthur trabalha no Ministério da Magia, no Departamento de Controle do Mau Uso dos Artefatos dos Trouxas. Ele é fascinado por tudo relacionado ao mundo dos trouxas e é conhecido por sua bondade e simplicidade.",
        familia: "Weasley",
        casa: "Grifinória",
        idade: 48,
        imagem: "./img/Arthur_Weasley.webp",
        habilidades: ["Feitiço de Reparação", "Alohomora", "Feitiço de Proteção"],
    },
    {
        nome: "Molly Weasley",
        descricao: "Matriarca da família Weasley, Molly é conhecida por sua hospitalidade, sendo uma excelente cozinheira e uma figura materna para Harry Potter. Ela é uma bruxa habilidosa, especialmente em feitiços domésticos e de proteção.",
        familia: "Weasley",
        casa: "Grifinória",
        idade: 47,
        imagem: "./img/Molly_Weasley.webp",
        habilidades: ["Feitiço de Limpeza", "Protego", "Expelliarmus"],
    },
    {
        nome: "Fred Weasley",
        descricao: "Um dos gêmeos Weasley, Fred era conhecido por seu senso de humor e talento para criar logros e truques mágicos com seu irmão George. Eles abriram a loja 'Gemialidades Weasley' juntos.",
        familia: "Weasley",
        casa: "Grifinória",
        idade: 20,
        imagem: "./img/Fred_Weasley.webp",
        habilidades: ["Feitiço de Transfiguração", "Bombarda", "Encantamentos de Ilusão"],
    },
    {
        nome: "George Weasley",
        descricao: "Irmão gêmeo de Fred, George é cofundador da 'Gemialidades Weasley'. Embora perca uma orelha durante a guerra contra Voldemort, ele mantém seu senso de humor e habilidade para inventar feitiços inovadores.",
        familia: "Weasley",
        casa: "Grifinória",
        idade: 20,
        imagem: "./img/George_Weasley.webp",
        habilidades: ["Encantamento de Expansão", "Feitiço de Ilusão", "Aparatação"],
    },
    {
        nome: "Percy Weasley",
        descricao: "Percy é o terceiro filho mais velho da família e muito ambicioso. Ele foi monitor e, mais tarde, trabalhou no Ministério da Magia, distanciando-se da família por algum tempo.",
        familia: "Weasley",
        casa: "Grifinória",
        idade: 23,
        imagem: "./img/Percy_Weasley.webp",
        habilidades: ["Aparatação", "Feitiço do Escudo", "Alohomora"],
    },
    {
        nome: "Gina Weasley",
        descricao: "A caçula da família Weasley e única filha, Gina é uma bruxa poderosa e determinada. Ela se torna uma jogadora talentosa de quadribol e, mais tarde, tem um relacionamento com Harry Potter.",
        familia: "Weasley",
        casa: "Grifinória",
        idade: 16,
        imagem: "./img/Gina_Weasley.webp",
        habilidades: ["Expelliarmus", "Feitiço do Patrono: um cavalo", "Bat-bogey Hex"],
    },
    {
        nome: "Rúbeo Hagrid",
        descricao: "Meio-gigante e Guardião das Chaves e Terrenos de Hogwarts, Hagrid é um grande amigo de Harry Potter e seus amigos. Conhecido por sua bondade e amor por criaturas mágicas, ele também foi professor de Trato das Criaturas Mágicas.",
        familia: "Hagrid",
        casa: "Grifinória",
        idade: 63,
        imagem: "./img/Rubeo_Hagrid.webp",
        habilidades: ["Controle sobre criaturas mágicas", "Força sobre-humana", "Resistência a feitiços"]
    }
];
